version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345  # Usa una contraseña segura
      - MYSQL_DATABASE=sysmedicdb
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - auth-networks


  node-app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    env_file:
      - .env
    ports:
      - "3030:3030"
    networks:
      - auth-networks
    command: npm start

networks:
  auth-networks:
    driver: bridge  

volumes:
  db_data:
