FROM node

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de configuración del paquete y los instalamos
COPY package*.json ./

RUN npm install

# Copiamos el resto del código de la aplicación
COPY . /app/.


# Comando para ejecutar la aplicación
CMD [ "npm", "start" ]